name: Publish Package

on:
  push:
    tags:
      - "v*" # i.e. v1.0, v20.15.10

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: test
        uses: rosmarinus-project/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}