name: Publish Package

on:
  push:
    tags:
      - "v*" # i.e. v1.0, v20.15.10
permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: test
        uses: rosmarinus-project/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}